name: .NET

on:
  push:
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Dependencies restore
      run: dotnet restore
    - name: Build
      run: dotnet build
    - uses: actions/upload-artifact@v2
      with:
        name: Hrishikesh's RPC - CI
        path: bin/Debug/Hrishikesh's RPC.exe
